### ISSUE TITLE
Last Development Strike!. Plugins, Anything!.

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1400]
#### Future development plugins & Things
* [x] = Development Complete

#### Todo
* [x] MassStart
* [x] AudioAPI
* [ ] IPBots v1.0.3
* [ ] Re-making Client (In Development **May takes a couple of weeks**)
* [ ] Coin System (Plugins w/ Client **Will be in development after client release**)
* [ ] Socket oguarl command remote handler (Plugin w/ Client) (In Development) (Will be used for stores, and client/global rewards based on the coin system, and player of the day titles)
* [ ] Side-online c++ project to manage ports, and protect from denial attacks (Windows, and Mono compatible)

#### Future Additions
* Client instructions can now contain MarkDown
* Notifications
* User auth
* Friendship, and messaging
* Customizable client settings
* 200+ more skins! (With some removed).
* Levels / Ranking system (Which will be global)
* Global chat
* Basic stores which on some servers you are allowed to purchase things. (Not monitored nor unfluecned by AJS)
* _And more.. Being updating_

**Comment by Souf123** [comment]
what is that coins system ?
+

**Comment by RevivedSol** [comment]
you should make a skin collum next to the nickname collum because some server their max name is 15 and after inputing the skin name the name is unusable. and also minimap, team tag like cik extension and maybe some shortcuts for commands like 6 for need a teammate or 5 for need backup at xx

**Comment by LegitSoulja** [comment]
@Souf The coin system is an optional plugin to be used. When used, some things will be locked for players. 

Players will be able to earn coins for playing on public servers that uses the coin system. You earn coins, not buy coins. You'll then be able to unlock skins, earn rewards, spend coins on power ups, and more.

@RevivedSol I recently created my own type of way skins will be shown.

I will fix nick Max length which skins names will not interfere with nick names.

Minimap has been a requested thing, but I don't know much about canvas api so I can't make the map.

Tags, clans, friends, levels, all coming soon aswell.

Since there's now site notifications, maybe using extra keybinds on a server specifically you can call for help, or whatever using some predefined keybinds

**Comment by Tokoagar** [comment]
For the coins system can u add skin adding from the config (if a plugin)?

**Comment by LegitSoulja** [comment]
@Tokoagar There will be alot of customizations.

**Comment by RevivedSol** [comment]
Wait u mean u guys gonna stop developing anymore ?? @LegitSoulja

**Comment by RevivedSol** [comment]
U can tell me what type of skin u guys want I will try to make it using photoshop

**Comment by RevivedSol** [comment]
I just need someone teach me how to code

**Comment by firelightning13** [comment]
@RevivedSol [Hold your horses m8](https://cloud.githubusercontent.com/assets/17120382/17516123/24a21e2e-5e6f-11e6-9079-41737479ff1c.png)

**Comment by RevivedSol** [comment]
@firelightning13  ok

**Comment by Tokoagar** [comment]
Thanks @LegitSoulja you are the best!
:)

**Comment by Tokoagar** [comment]
Levels / Ranking system: When it says global does it mean it's not in the server

**Comment by LegitSoulja** [comment]
No, it's all client server side.

**Comment by LegitSoulja** [comment]
But servers can retrieve that information :)

**Comment by LegitSoulja** [comment]
I may even run the client as a server instead of basting it with Aka Apache

**Comment by LegitSoulja** [comment]
Using* not blasting. Sorry. I'm on mobile

**Comment by SharkFinPro** [comment]
@LegitSoulja Can't u just edit your post?

**Comment by SharkFinPro** [comment]
:P

**Comment by LegitSoulja** [comment]
Not on mobile unless is request desktop.. Then it's all wierd. It's a waste of time. Then I know someone, or I would eventually go back and fix lol.

**Comment by UltraSirius** [comment]
But hey we could add some music in background Music? DJ System right? but we dont know how.. i want to add background music only.. (If u guys are interested)

**Comment by Agarian** [comment]
That sounds like a cool idea, having the option to play music through the server!

**Comment by SharkFinPro** [comment]
How would i make a plugin that is JS that cna use Audio() - it seems weird with ogarUL

**Comment by LegitSoulja** [comment]
That can use audio? Have you looked into html5?

**Comment by LegitSoulja** [comment]
Or you mean, send audio to the client from server? 

I was going to make a plugin to support YouTube and soundcloud support to play music, or have YouTube as the canvas background. 

I was going to do this, but never did yet. If this is something you recommend then let me know then I'll think about adding it

**Comment by SharkFinPro** [comment]
do that =)

**Comment by Agarian** [comment]
Totally

**Comment by LegitSoulja** [comment]
@SharkFinPro I'm done. It only works with the new client. If you want to test it then contact me on skype. I'll release the plugin when I release the client because there wont be no use for it until the new client is released.

Some people already have the plugin, but they are experimenting more with it.

**Comment by SharkFinPro** [comment]
ok :D

**Comment by LegitSoulja** [comment]
@RevivedSol yes, I'm doing my last things of development before leaving completely..

**Comment by UltraSirius** [comment]
The Audio System will autimaticlly play when u opened Ogarul.tk  with is powered by Youtube,SoundCloud Or MP3,

**Comment by LegitSoulja** [comment]
@UltraSirius  im not planning of being with ogar. It was fun at first, but I barely even play anymore.

**AudioAPI** - You are able to play selected songs from youtube, and or soundcloud and play it for everyone who is connected to the client. Sending MP3 files, and such to the client will not happen because its too much, and plus I doubt trying to send a MP3 would even work with sockets.

**Comment by UltraSirius** [comment]
@LegitSoulja OH thats why.. Sorry For Asking.. Well..! KEEP IT UP FOR creating NEW PLUGINS!

**Comment by LegitSoulja** [comment]
@UltraSirius Um.. You said MP3, which gave me an idea of having audio.ogarul.tk for people to upload there own song, and have it preloaded instead of using youtube.

Youtube on the other end, I have a solution for making youtube not lag.. Which is the same as preloading, but better. You'll see when released.

**Comment by RevivedSol** [comment]
what about the child processes ? one more to go right ? is @Andrews54757  still work on it ?

**Comment by LegitSoulja** [comment]
He's working on a lot of things.. Just not ogarul/child processes. Just give him a break. Don't put too much pressure on him. There's barely nobody here that can even help him out with this project. 

I did the best I could whilst I was here with maintaining things and what not, but eh. Don't be to hard on him. That's goes for you, and everyone else. Things will eventually be finished then released. There's no specific date, nor time of when he finishes. Just be patient, or do something else other than playing Ogar :/

**Comment by LegitSoulja** [comment]
Closing for now
