### ISSUE TITLE
New OgarUl Statistics

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#803]
#### OgarUl Private Servers

Website: [stats.ogarul.tk](http://stats.ogarul.tk/)

Install the Statistics plugin for your server to be added to the list.
_**Your stat port has to be open also for this plugin to work!**_

#### **Install Usage**
> plugin install Statistics

#### **Commands**

- stats [delete, create, abort, refresh]

- **stats delete**
Delete your current stats, and disable stats update until restart

- **stats create**
If your status somehow is not showing, use this command

- **stats abort**
If you just want to delete all your stats and the plugin this is the command you are looking for 

#### **Config**

- 0 = false, 1 = true
- **serverName**(text)
Your unique specfic name for your server

- **alerts**(int)
Enable alerts abouts stats on connections and updates via statistics

- **uservpsip**(text)
If enabled(1) your VPS ip will be updated. Use (0) to use customip/domain

- **optout**(int)
If you want to opt out, and keep the plugin but delete server statistics, turn this on(1)  

- **clientlink**(text)
 If you have another client besides ogarul client you can add one ex(http://play.ogarul.tk/?ip=localhost:443) < direct client link to your server & client
by default, clientlink if null will use player.ogarul.tk client instead of agar.io or any other.

[DEV]
- **debug**(int)
If you want to see more information output in your console you might not even understand but be my guest..

#### Todo List
Additions:
- [ ] Add port checker to check if port open.
- [x] Add connection speed testing.
- [ ] Add game time Responce.
- [x] Add enable and disable commands.
- [ ] Add edit config via command ability.
- [ ] Add public top player to leaderboard.
- [ ] More extra server feedback like ( uptime, connection speed)
- [ ] _Thinking about uws for faster and live stats_. 
- [ ] Add plugin integration to obtain certain information.
New Stats
- [x] Connection speed
- [ ] Game Responce time
- [ ] Top Player (TP)
Server side
- [ ] Get rid of extra work.
- [ ] Convert server into classes (May boost speeds)
- [x] Better UI, smoother layout. 
- [x] Better minimum table display.
- [x] Live updates tables.

_Please note **Statistics** just released and new features will be added eventually!. Also check out the configuration file for **Statistics** to set your server name and such._

**Comment by systemroot** [comment]
Can i create a plugin which we can view live RAM & CPU Usage ?! I think is a good idea.

**Comment by David1ali12** [comment]
@LegitSoulja  can I turn off or on server from stats ?

**Comment by LegitSoulja** [comment]
@David1ali12 Yes, Im implementing it.

**Comment by LegitSoulja** [comment]
@systemroot It would be easy, and sure you can. You can develop plugins and share here with us :)

**Comment by Andrews54757** [comment]
@LegitSoulja Should I review and if needed re-code the plugin?

**Comment by systemroot** [comment]
@LegitSoulja @Andrews54757 Any answer for [This](https://github.com/AJS-development/Ogar-unlimited/issues/804) Please :confused:

**Comment by David1ali12** [comment]
i got an problem the plugin gets the ip but am hosting with domain mind only connect with domain like urs s1.agariohub.tk it get the ip which cant be connected with that ip.

**Comment by LegitSoulja** [comment]
@Andrews54757 when i finished. I have a new layout :)

**Comment by LegitSoulja** [comment]
@David1ali12 Haha, Yea, I didn't add that to the plugin yet. Im gonna release it soon so you will be able to not only use your vps ip

**Comment by Andrews54757** [comment]
@LegitSoulja I tested your plugin and we seriously need to create a filter. Why dont you for the layout, hide all servers that has a invalid ping? Then have  a button to show them

**Comment by David1ali12** [comment]
it lists local ip on website :/ I run it from my pc and it list it

**Comment by LegitSoulja** [comment]
@Andrews54757 on the site? Remove all the bad pings instead of showing them?

In the plugin im using a port ping test to see if the port open. Everything updates on server responce.

**Comment by LegitSoulja** [comment]
@Andrews54757 im doing less work on nodejs side, and more on the server if you havent checked it out yet. I just recently updated again with some new features, like deletions, and aborts. /\ updated issue

**Comment by raphyjb** [comment]
SITE DOWN

**Comment by LegitSoulja** [comment]
@raphyjb Yes, early I fixed that problem. There shouldn't be no more site downtime :). Also re-update the plugin

**Comment by raphyjb** [comment]
Hm still ur site is down.... This is spamming my console too.....
Could not send data
[Statistics] , Updated Server Bots , Updated Recent Player
[Statistics] , Updated Recent Player
[Statistics] , Updated Recent Player
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Could not send data
Is there a way to put more of a time between each, its like each 2 seconds it sends it..

**Comment by LegitSoulja** [comment]
@raphyjb opt out by setting 1 in the config. I don't know why you cannot connect. Are you able to view http://stats.ogarul.tk from what you are hosting the server on? Are there any blocked connections?

When was the last time you restarted? or update the plugin?

**Comment by raphyjb** [comment]
lol Legit need help mines says it offline IN RED :(

**Comment by DarkZYT** [comment]
Please can u help , why do my serv appear then disappear when i open stats.ogarul.tk , it goes red and they say its offline ??!

**Comment by LegitSoulja** [comment]
@DarkZYT @raphyjb

When you are running the server on the same computer viewing stats.ogarul.tk you won't see your own server connecting because your public IP address doesn't know what to do when trying to connect to you. Here's a few ways to make sure that it's working.

- Make sure your stat port is open. This is used to grab leaderboard stats, and also check connectivity between servers.
- Use a online open port checker to make sure that your port is open. If it's open, it's public for people's view.

Don't worry about not being able to see your stats. You could use your phone w/ mobile network and not wifi to test it yourself.

**Comment by Agarian** [comment]
Cool
